---
apiVersion: v1
kind: Service
metadata:
  name: apache-artemis-web
spec:
  type: NodePort
  selector:
    app: apache-artemis
  ports:
    - name: admin-console
      port: 8161
      targetPort: 8161
---
apiVersion: v1
kind: Service
metadata:
  name: apache-artemis-amqp
spec:
  type: NodePort
  selector:
    app: apache-artemis
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-artemis
spec:
  selector:
    matchLabels:
      app: apache-artemis
  template:
    metadata:
      labels:
        app: apache-artemis
    spec:
      containers:
        - name: broker
          image: quay.io/rhdevelopers/apache-artemis:2.6.4
          ports:
            - containerPort: 8161
              protocol: TCP
              name: admin-console
            - containerPort: 5672
              protocol: TCP
              name: amqp
