apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source            
spec:
  bootstrapServers:
   - my-cluster-kafka-bootstrap.amex-kafka:9092
  topics:
   - my-topic              
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: eventinghello

